github.com:
    users:
        subinoybiswas:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: subinoybiswas
